[package]
version = "0.2.0"
name = "ev-hyperlane-program"
edition = "2021"

[dependencies]
alloy-primitives = { workspace = true }
ev-zkevm-types = { workspace = true }
sp1-zkvm = { workspace = true }
