defaultHook:
  address: "0xFCb1d485ef46344029D9E8A7925925e146B3430E"
  beneficiary: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
  maxProtocolFee: "0"
  owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
  protocolFee: "0"
  type: protocolFee
defaultIsm:
  address: "0xa05915fD6E32A1AA7E67d800164CaCB12487142d"
  type: testIsm
interchainAccountRouter:
  address: "0x9F098AE0AC3B7F75F0B3126f471E5F592b47F300"
  commitmentIsm:
    address: "0xc5891D3385DFC2f430494bd8B773Ac43D737244d"
    owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
    type: offchainLookupIsm
    urls:
      - https://commitment-read-ism.hyperlane.xyz
  hook: "0x0000000000000000000000000000000000000000"
  interchainSecurityModule:
    address: "0x9F098AE0AC3B7F75F0B3126f471E5F592b47F300"
    isms: {}
    owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
    type: interchainAccountRouting
  mailbox: "0xb1c938F5BA4B3593377F399e12175e8db0C787Ff"
  owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
  remoteRouters: {}
owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
proxyAdmin:
  address: "0x7e7aD18Adc99b94d4c728fDf13D4dE97B926A0D8"
  owner: "0xaF9053bB6c4346381C77C2FeD279B17ABAfCDf4d"
requiredHook:
  address: "0x1D957dA7A6988f5a9d2D2454637B4B7fea0Aeea5"
  type: merkleTreeHook
